lebondeal/Models/Messages.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace lebondeal.Models
{
    public class Message
    {
        [Key]
        public int messageId { get; set; }
        [Required]
        public string messageName { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string messageEmail { get; set; }
        [Required]
        public string messageSubject { get; set; }
        [Required]
        public string messageContent { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime messageDate { get; set; }


    }
}

lebondeal/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using lebondeal.Models;
using lebondeal.Services;
using lebondeal.ViewModels;

namespace lebondeal.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public async Task<ActionResult> Index()
        {
            var cart = new Cart(HttpContext);
            var items = await cart.GetCartItemsAsync();
            var cartViewModel = new CartViewModel
            {
                Items = items,
                Total = CalcuateCart(items)

            };
            return View(cartViewModel);
        }
        //Ajouter au panier
        public async  Task<ActionResult> AddToCart(int id)
        {
            
            var cart = new Cart(HttpContext);
            await cart.AddAsync(id);
            //retour à l'index
            return RedirectToAction("index");
        }
        //checkout 
        [HttpGet]
        public  ActionResult Checkout()
        {


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Checkout(CheckoutViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var cart = new Cart(HttpContext);

            var result = await cart.CheckoutAsync(model);

            if (result.Succeeded)
            {
                //en cas de succes de la transaction
                TempData["transactionId"] = result.TransactionId;
                return RedirectToAction("Complete");
            }

            ModelState.AddModelError(string.Empty, result.Message);

            return View(model);
        }
        //supprimer du panier 
        public async Task<ActionResult> RemoveToCart(int id)
        {

            var cart = new Cart(HttpContext);
            await cart.RemoveAsync(id);
            //retour à l'index
            return RedirectToAction("index");
        }

        //supprimer du definitivement 
        public async Task<ActionResult> RemoveFromCart(int id)
        {

            var cart = new Cart(HttpContext);
            await cart.RemoveFromCartAsync(id);
            //retour à l'index
            return RedirectToAction("index");
        }

        //action complete lorsque le paiment est fait
        public ActionResult Complete()
        {
            ViewBag.TransactionId = (string)TempData["transactionId"];

            return View();
        }
        //fonction qui calcule le total 
        private static decimal CalcuateCart(IEnumerable<CartItem> items)
        {
            //nombre decimal
            return items.Sum(item => (item.Product.Price*item.Count));
        }
    }
}

lebondeal/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using lebondeal.Data;
using lebondeal.Models;
using lebondeal.Services;

namespace lebondeal.Controllers
{
    public class StoreController : Controller
    {
        //les controleurs par défaut
        private readonly StoreService _store;
        public StoreController() : this(new StoreService()) { }
        public StoreController(StoreService service)
        {
            _store = service;
            
        }
        // GET: Store
        public async Task<ActionResult> Index()
        {
            var slides = await _store.GetAllSliderAsync();
            return View(slides);
        }
        //afficher une category 
        public async Task<ActionResult> Browse(string id)
        {
            var products = await _store.GetProductsForAsync(id);

            if (!products.Any())
            {
                return HttpNotFound();
            }

            return View(products);
        }

        //page de contact
        [HttpGet]
        public  ActionResult Contact()
        {
            return View(new Message());
        }

        [HttpPost]
        public async Task <ActionResult> Contact(Message model)
        {
            if (!ModelState.IsValid)
            {
                //on retourne la vue en lui passant le model
                return View(model);

            }
                model.messageDate = DateTime.Now;
               await _store.CreateMessage(model);
                return RedirectToAction("Contact");
           
            return View();
        }

        //details d'un produit
        public async Task<ActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return HttpNotFound();
            }

            var product = await _store.GetProductByIdAsync(id.Value);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }


        //electro-menager
        public async Task<ActionResult> Electro()
        {
            var products = await  _store.GetAllProductByIdAsync(3);

            return View(products);
        }

        //telephonie
        public async Task<ActionResult> Telephonie()
        {
            var products = await _store.GetAllProductByIdAsync(1);

            return View(products);
        }


        //informatique
        public async Task<ActionResult> Informatique()
        {
            var products = await _store.GetAllProductByIdAsync(8);

            return View(products);
        }

        //games
        public async Task<ActionResult> Games()
        {
            var products = await _store.GetAllProductByIdAsync(9);

            return View(products);
        }

        //hifi
        public async Task<ActionResult> Hifi()
        {
            var products = await _store.GetAllProductByIdAsync(10);

            return View(products);
        }

        //images
        public async Task<ActionResult> Picture()
        {
            var products = await _store.GetAllProductByIdAsync(11);

            return View(products);
        }


    }
}

lebondeal/Views/Store/Contact.cshtml
@model lebondeal.Models.Message
@Html.Partial("_messageForm", Model)

lebondeal/Views/Store/Details.cshtml
 @model lebondeal.Models.Product

@{
    ViewBag.Title = Model.Name;
}

    <div class="product-details">
        <!--product-details-->
        <div class="col-sm-5">
            <div class="view-product">
                <img src=" ~/Areas/Cockpit/Images/Produits/@Model.ImgUrl" alt=""/>
            </div>
           

        </div>
        <div class="col-sm-7">
            <div class="product-information">
                <!--/product-information-->
                <h2>@Model.Name</h2>
                <p>@Model.Description</p>
                <span>
                    <span>@Model.Price €</span>
                    <a href="@Url.Action("AddToCart", "Cart", new {id = @Model.ProductId})">
                        <button type="button" class="btn btn-fefault cart">
                            <i class="fa fa-shopping-cart"></i>
                            Ajouter au panier
                        </button>
                    </a>
                        
                </span>
            </div><!--/product-information-->
        </div>
    </div>

lebondeal/Views/Store/Index.cshtml
@model IEnumerable<lebondeal.Models.Slider>
@{
    ViewBag.Title = "lebondeal la boutique";
}

<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        @for (var i = 0; i < Model.Count(); i++)
                        {
                            if (i == 0)
                            {
                                <li data-target="#slider-carousel" data-slide-to="@i" class="active"></li>
                            }
                            else
                            {
                                <li data-target="#slider-carousel" data-slide-to="@i"></li>
                            }


                        }
                    </ol>

                    <div class="carousel-inner">
                  @{

                      var it = 0;
                  }
                 @foreach (var item in Model)
                 {
                     if (it == 0)
                     {
                         <div class="item active">
                             <div class="col-sm-6">
                                 <h2>@item.Title</h2>
                                 <p>@item.Text </p>
                                 <button type="button" class="btn btn-default get">Get it now</button>
                             </div>
                             <div class="col-sm-6">
                                 <img src="~/Areas/Cockpit/Images/Slides/@item.Img" class="girl img-responsive" alt="@item.Title"/>
                                 <!-- <img src="images/home/pricing.png" class="pricing" alt=""/> -->
                             </div>
                         </div>

                     }
                     else
                     {
                        <div class="item">
                            <div class="col-sm-6">
                                <h2>@item.Title</h2>
                                <p>@item.Text </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/Areas/Cockpit/Images/Slides/@item.Img" class="girl img-responsive" alt="@item.Title" />
                                <!-- <img src="images/home/pricing.png" class="pricing" alt="" />  -->
                            </div>
                        </div>


                     }
                     it++;
                 }
                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->

lebondeal/Views/Store/Telephonie.cshtml
@model  IEnumerable<lebondeal.Models.Product>
@{
    ViewBag.Title = "Telephonie";
}

<div class="features_items">
    @foreach (var item in Model)
            {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                        <h2>@item.Price €</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                        <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

lebondeal/Views/Store/_messageForm.cshtml
@model lebondeal.Models.Message
@{
    ViewBag.Title = "Contact";
}


<div id="contact-page" class="container">
    <div class="bg">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="title text-center">Contact</h2>
                <div id="gmap" class="contact-map">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="contact-form">
                    <h2 class="title text-center">contactez-nous</h2>
                    <div class="status alert alert-success" style="display: none"></div>
                    <form id="main-contact-form"  action="@Url.Action("Contact")" class="contact-form row" name="contact-form" method="post">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group col-md-6">
                            @Html.EditorFor(model => model.messageName, new { htmlAttributes = new { @class = "form-control",@placeholder= "Votre nom" } })
                            @Html.ValidationMessageFor(model => model.messageName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.EditorFor(model => model.messageEmail, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                            @Html.ValidationMessageFor(model => model.messageEmail, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-12">
                            @Html.EditorFor(model => model.messageSubject, new { htmlAttributes = new { @class = "form-control",@placeholder="sujet" } })
                            @Html.ValidationMessageFor(model => model.messageSubject, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-12">
                            <textarea name="messageContent" data-val="true" id="message" required="required" class="form-control" rows="8" placeholder="votre message"></textarea>
                            @Html.ValidationMessageFor(model => model.messageContent, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-12">
                            <input type="submit" name="submit" class="btn btn-primary pull-right" value="Valider">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="contact-info">
                    <h2 class="title text-center">Contact Info</h2>
                    <address>
                        <p>Lebondeal SA.</p>
                        <p>Paris france</p>
                        <p>Ile de France</p>
                        <p>Mobile: +2346 17 38 93</p>
                        <p>Fax: 1-714-252-0026</p>
                        <p>Email: info@lebondeal.fr</p>
                    </address>
                    <div class="social-networks">
                        <h2 class="title text-center">Social Networking</h2>
                        <ul>
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-youtube"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/#contact-page-->

lebondeal/Views/Store/electro.cshtml
@model  IEnumerable<lebondeal.Models.Product>
    @{
        ViewBag.Title = "Electro";
    }
           
        <div class="features_items">
        @foreach (var item in Model)
            {
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                                    <h2>@item.Price €</h2>
                                    <p>@item.Name</p>
                                    <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                                    <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                                </div>          
                        </div>
                    </div>
                </div>

            }
        </div>

lebondeal/Views/Store/games.cshtml
@model  IEnumerable<lebondeal.Models.Product>
@{
    ViewBag.Title = "Jeux-videos";
}

<div class="features_items">
    @foreach (var item in Model)
            {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                        <h2>@item.Price €</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                        <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

lebondeal/Views/Store/hifi.cshtml
@model  IEnumerable<lebondeal.Models.Product>
@{
    ViewBag.Title = "hifi";
}

<div class="features_items">
    @foreach (var item in Model)
            {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                        <h2>@item.Price €</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                        <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

lebondeal/Views/Store/informatique.cshtml
@model  IEnumerable<lebondeal.Models.Product>
@{
    ViewBag.Title = "Informatique";
}

<div class="features_items">
    @foreach (var item in Model)
            {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                        <h2>@item.Price €</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                        <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

lebondeal/Views/Store/picture.cshtml
@model  IEnumerable<lebondeal.Models.Product>
@{
    ViewBag.Title = "Images";
}

<div class="features_items">
    @foreach (var item in Model)
            {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Areas/Cockpit/Images/Produits/@item.ImgUrl" alt="">
                        <h2>@item.Price €</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("AddToCart", "Cart", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
                        <a href="@Url.Action("Details", "Store", new {id = @item.ProductId})" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>